import type { AppLanguage } from './types';
import { CLOUDFLARE_SAFETY_UPGRADE_MESSAGE } from './cloudflare';

type Translations = Partial<Record<AppLanguage, string>> & { en: string };
const languages = ['en', 'fr', 'de', 'pt', 'it', 'tr', 'zh-CN', 'zh-TW', 'ja', 'ko'] as const;
type ErrorRow = [string, string, string, string, string, string, string, string, string, string, string];

// Keep the actual safety/recovery reason through IPC instead of replacing it with
// a generic error. Portuguese wording in these rows is shared by both variants.
const rows: ErrorRow[] = [
  ['Cloudflare no confirmó todas las versiones de la biblioteca.', 'Cloudflare did not acknowledge every Library version.', 'Cloudflare n’a pas confirmé toutes les versions de la bibliothèque.', 'Cloudflare hat nicht alle Bibliotheksversionen bestätigt.', 'A Cloudflare não confirmou todas as versões da biblioteca.', 'Cloudflare non ha confermato tutte le versioni della libreria.', 'Cloudflare tüm kitaplık sürümlerini onaylamadı.', 'Cloudflare 未确认所有资料库版本。', 'Cloudflare 未確認所有資料庫版本。', 'Cloudflare がすべてのライブラリバージョンを確認しませんでした。', 'Cloudflare가 모든 라이브러리 버전을 확인하지 않았습니다.'],
  ['La actualización Yjs supera 8 MiB.', 'The Yjs update exceeds 8 MiB.', 'La mise à jour Yjs dépasse 8 MiB.', 'Das Yjs-Update überschreitet 8 MiB.', 'A atualização Yjs excede 8 MiB.', 'L’aggiornamento Yjs supera 8 MiB.', 'Yjs güncellemesi 8 MiB sınırını aşıyor.', 'Yjs 更新超过 8 MiB。', 'Yjs 更新超過 8 MiB。', 'Yjs の更新が 8 MiB を超えています。', 'Yjs 업데이트가 8 MiB를 초과합니다.'],
  ['El adjunto supera el tamaño permitido.', 'The attachment exceeds the allowed size.', 'La pièce jointe dépasse la taille autorisée.', 'Der Anhang überschreitet die zulässige Größe.', 'O anexo excede o tamanho permitido.', 'L’allegato supera le dimensioni consentite.', 'Ek izin verilen boyutu aşıyor.', '附件超过允许的大小。', '附件超過允許的大小。', '添付ファイルが許容サイズを超えています。', '첨부파일이 허용 크기를 초과합니다.'],
  ['El servidor devolvió un rango de adjunto incorrecto.', 'The server returned an incorrect attachment range.', 'Le serveur a renvoyé une plage incorrecte pour la pièce jointe.', 'Der Server hat einen falschen Bytebereich des Anhangs zurückgegeben.', 'O servidor devolveu um intervalo incorreto do anexo.', 'Il server ha restituito un intervallo errato dell’allegato.', 'Sunucu ek için yanlış bir bayt aralığı döndürdü.', '服务器返回了错误的附件字节范围。', '伺服器傳回了錯誤的附件位元組範圍。', 'サーバーが添付ファイルの誤ったバイト範囲を返しました。', '서버가 잘못된 첨부파일 바이트 범위를 반환했습니다.'],
  ['Una fila supera el límite de publicación de Cloudflare.', 'A row exceeds the Cloudflare publication limit.', 'Une ligne dépasse la limite de publication de Cloudflare.', 'Eine Zeile überschreitet das Veröffentlichungslimit von Cloudflare.', 'Uma linha excede o limite de publicação da Cloudflare.', 'Una riga supera il limite di pubblicazione di Cloudflare.', 'Bir satır Cloudflare yayımlama sınırını aşıyor.', '某一行超过 Cloudflare 的发布限制。', '某一列超過 Cloudflare 的發佈限制。', '行が Cloudflare の公開上限を超えています。', '행이 Cloudflare 게시 한도를 초과합니다.'],
  ['Cloudflare devolvió un tamaño de parte no válido. Se ha detenido la publicación.', 'Cloudflare returned an invalid part size. Publication has stopped.', 'Cloudflare a renvoyé une taille de partie invalide. La publication a été arrêtée.', 'Cloudflare hat eine ungültige Teilgröße zurückgegeben. Die Veröffentlichung wurde gestoppt.', 'A Cloudflare devolveu um tamanho de parte inválido. A publicação foi interrompida.', 'Cloudflare ha restituito una dimensione di parte non valida. La pubblicazione è stata interrotta.', 'Cloudflare geçersiz bir parça boyutu döndürdü. Yayımlama durduruldu.', 'Cloudflare 返回了无效的分块大小。发布已停止。', 'Cloudflare 傳回了無效的分塊大小。發佈已停止。', 'Cloudflare が無効なパートサイズを返しました。公開を停止しました。', 'Cloudflare가 잘못된 파트 크기를 반환했습니다. 게시가 중지되었습니다.'],
  ['La publicación alcanzó el límite de seguridad de llamadas a Cloudflare.', 'Publication reached the safety limit for Cloudflare requests.', 'La publication a atteint la limite de sécurité des requêtes Cloudflare.', 'Die Veröffentlichung hat das Sicherheitslimit für Cloudflare-Anfragen erreicht.', 'A publicação atingiu o limite de segurança de pedidos à Cloudflare.', 'La pubblicazione ha raggiunto il limite di sicurezza delle richieste a Cloudflare.', 'Yayımlama Cloudflare istekleri için güvenlik sınırına ulaştı.', '发布已达到 Cloudflare 请求的安全上限。', '發佈已達到 Cloudflare 請求的安全上限。', '公開処理が Cloudflare リクエストの安全上限に達しました。', '게시가 Cloudflare 요청 안전 한도에 도달했습니다.'],
  ['Cloudflare devolvió una página sin avanzar el cursor. Se ha detenido la sincronización.', 'Cloudflare returned a page without advancing the cursor. Synchronization has stopped.', 'Cloudflare a renvoyé une page sans faire avancer le curseur. La synchronisation a été arrêtée.', 'Cloudflare hat eine Seite ohne Fortschritt des Cursors zurückgegeben. Die Synchronisierung wurde gestoppt.', 'A Cloudflare devolveu uma página sem avançar o cursor. A sincronização foi interrompida.', 'Cloudflare ha restituito una pagina senza avanzare il cursore. La sincronizzazione è stata interrotta.', 'Cloudflare imleci ilerletmeden bir sayfa döndürdü. Eşitleme durduruldu.', 'Cloudflare 返回了未推进游标的页面。同步已停止。', 'Cloudflare 傳回了未推進游標的頁面。同步已停止。', 'Cloudflare がカーソルを進めずにページを返しました。同期を停止しました。', 'Cloudflare가 커서를 이동하지 않고 페이지를 반환했습니다. 동기화가 중지되었습니다.'],
  ['Cloudflare contiene un cambio que no se pudo aplicar.', 'Cloudflare contains a change that could not be applied.', 'Cloudflare contient une modification qui n’a pas pu être appliquée.', 'Cloudflare enthält eine Änderung, die nicht angewendet werden konnte.', 'A Cloudflare contém uma alteração que não foi possível aplicar.', 'Cloudflare contiene una modifica che non è stato possibile applicare.', 'Cloudflare uygulanamayan bir değişiklik içeriyor.', 'Cloudflare 包含无法应用的更改。', 'Cloudflare 包含無法套用的變更。', 'Cloudflare に適用できなかった変更があります。', 'Cloudflare에 적용할 수 없는 변경 사항이 있습니다.'],
  ['Un cambio del relay no pudo aplicarse.', 'A relay change could not be applied.', 'Une modification du relais n’a pas pu être appliquée.', 'Eine Relay-Änderung konnte nicht angewendet werden.', 'Não foi possível aplicar uma alteração do relay.', 'Non è stato possibile applicare una modifica del relay.', 'Bir aktarım değişikliği uygulanamadı.', '无法应用中继中的更改。', '無法套用轉送中的變更。', 'リレーの変更を適用できませんでした。', '릴레이 변경 사항을 적용할 수 없습니다.'],
  ['La publicación de Cloudflare se ha detenido.', 'Cloudflare publication has stopped.', 'La publication Cloudflare a été arrêtée.', 'Die Cloudflare-Veröffentlichung wurde gestoppt.', 'A publicação na Cloudflare foi interrompida.', 'La pubblicazione su Cloudflare è stata interrotta.', 'Cloudflare yayımlaması durduruldu.', 'Cloudflare 发布已停止。', 'Cloudflare 發佈已停止。', 'Cloudflare の公開を停止しました。', 'Cloudflare 게시가 중지되었습니다.'],
  ['El snapshot supera el límite de descarga de 512 MiB.', 'The snapshot exceeds the 512 MiB download limit.', 'L’instantané dépasse la limite de téléchargement de 512 MiB.', 'Der Snapshot überschreitet das Downloadlimit von 512 MiB.', 'O snapshot excede o limite de transferência de 512 MiB.', 'L’istantanea supera il limite di download di 512 MiB.', 'Anlık görüntü 512 MiB indirme sınırını aşıyor.', '快照超过 512 MiB 下载上限。', '快照超過 512 MiB 下載上限。', 'スナップショットがダウンロード上限の 512 MiB を超えています。', '스냅샷이 512 MiB 다운로드 한도를 초과합니다.'],
  ['El snapshot supera el límite de importación de 256 MiB.', 'The snapshot exceeds the 256 MiB import limit.', 'L’instantané dépasse la limite d’importation de 256 MiB.', 'Der Snapshot überschreitet das Importlimit von 256 MiB.', 'O snapshot excede o limite de importação de 256 MiB.', 'L’istantanea supera il limite di importazione di 256 MiB.', 'Anlık görüntü 256 MiB içe aktarma sınırını aşıyor.', '快照超过 256 MiB 导入上限。', '快照超過 256 MiB 匯入上限。', 'スナップショットがインポート上限の 256 MiB を超えています。', '스냅샷이 256 MiB 가져오기 한도를 초과합니다.'],
  ['El snapshot remoto no tiene un formato válido.', 'The remote snapshot has an invalid format.', 'Le format de l’instantané distant est invalide.', 'Der entfernte Snapshot hat ein ungültiges Format.', 'O snapshot remoto tem um formato inválido.', 'L’istantanea remota ha un formato non valido.', 'Uzak anlık görüntünün biçimi geçersiz.', '远程快照的格式无效。', '遠端快照的格式無效。', 'リモートスナップショットの形式が無効です。', '원격 스냅샷 형식이 잘못되었습니다.'],
  ['El snapshot requiere una versión de Nodus más reciente o tiene un esquema inválido.', 'The snapshot requires a newer Nodus version or has an invalid schema.', 'L’instantané nécessite une version plus récente de Nodus ou possède un schéma invalide.', 'Der Snapshot erfordert eine neuere Nodus-Version oder hat ein ungültiges Schema.', 'O snapshot requer uma versão mais recente do Nodus ou tem um esquema inválido.', 'L’istantanea richiede una versione più recente di Nodus o ha uno schema non valido.', 'Anlık görüntü daha yeni bir Nodus sürümü gerektiriyor veya şeması geçersiz.', '快照需要更新版本的 Nodus，或其架构无效。', '快照需要更新版本的 Nodus，或其結構描述無效。', 'スナップショットには新しい Nodus バージョンが必要か、スキーマが無効です。', '스냅샷에 더 최신 Nodus 버전이 필요하거나 스키마가 잘못되었습니다.'],
  ['El snapshot contiene tablas inválidas.', 'The snapshot contains invalid tables.', 'L’instantané contient des tables invalides.', 'Der Snapshot enthält ungültige Tabellen.', 'O snapshot contém tabelas inválidas.', 'L’istantanea contiene tabelle non valide.', 'Anlık görüntü geçersiz tablolar içeriyor.', '快照包含无效的表。', '快照包含無效的資料表。', 'スナップショットに無効なテーブルが含まれています。', '스냅샷에 잘못된 테이블이 포함되어 있습니다.'],
  ['El snapshot supera el límite de dos millones de filas.', 'The snapshot exceeds the limit of two million rows.', 'L’instantané dépasse la limite de deux millions de lignes.', 'Der Snapshot überschreitet das Limit von zwei Millionen Zeilen.', 'O snapshot excede o limite de dois milhões de linhas.', 'L’istantanea supera il limite di due milioni di righe.', 'Anlık görüntü iki milyon satır sınırını aşıyor.', '快照超过两百万行的上限。', '快照超過兩百萬列的上限。', 'スナップショットが 200 万行の上限を超えています。', '스냅샷이 200만 행 한도를 초과합니다.'],
  ['El snapshot supera el límite de diez mil imágenes.', 'The snapshot exceeds the limit of ten thousand images.', 'L’instantané dépasse la limite de dix mille images.', 'Der Snapshot überschreitet das Limit von zehntausend Bildern.', 'O snapshot excede o limite de dez mil imagens.', 'L’istantanea supera il limite di diecimila immagini.', 'Anlık görüntü on bin görüntü sınırını aşıyor.', '快照超过一万张图片的上限。', '快照超過一萬張圖片的上限。', 'スナップショットが 1 万枚の画像の上限を超えています。', '스냅샷이 이미지 1만 개 한도를 초과합니다.'],
  ['El snapshot contiene referencias de imágenes inválidas.', 'The snapshot contains invalid image references.', 'L’instantané contient des références d’images invalides.', 'Der Snapshot enthält ungültige Bildverweise.', 'O snapshot contém referências de imagens inválidas.', 'L’istantanea contiene riferimenti a immagini non validi.', 'Anlık görüntü geçersiz görüntü başvuruları içeriyor.', '快照包含无效的图片引用。', '快照包含無效的圖片參照。', 'スナップショットに無効な画像参照が含まれています。', '스냅샷에 잘못된 이미지 참조가 포함되어 있습니다.'],
  ['Las referencias de imágenes superan 2 MiB.', 'Image references exceed 2 MiB.', 'Les références d’images dépassent 2 MiB.', 'Die Bildverweise überschreiten 2 MiB.', 'As referências de imagens excedem 2 MiB.', 'I riferimenti alle immagini superano 2 MiB.', 'Görüntü başvuruları 2 MiB sınırını aşıyor.', '图片引用超过 2 MiB。', '圖片參照超過 2 MiB。', '画像参照が 2 MiB を超えています。', '이미지 참조가 2 MiB를 초과합니다.'],
  ['La importación de la réplica se ha cancelado.', 'Replica import was cancelled.', 'L’importation de la réplique a été annulée.', 'Der Replikatimport wurde abgebrochen.', 'A importação da réplica foi cancelada.', 'L’importazione della replica è stata annullata.', 'Kopya içe aktarımı iptal edildi.', '副本导入已取消。', '副本匯入已取消。', 'レプリカのインポートをキャンセルしました。', '복제본 가져오기가 취소되었습니다.'],
  ['La descarga del snapshot ha superado el plazo máximo.', 'The snapshot download exceeded its deadline.', 'Le téléchargement de l’instantané a dépassé le délai maximal.', 'Der Snapshot-Download hat das Zeitlimit überschritten.', 'A transferência do snapshot excedeu o prazo máximo.', 'Il download dell’istantanea ha superato il tempo massimo.', 'Anlık görüntü indirme işlemi zaman sınırını aştı.', '快照下载超过了时间上限。', '快照下載超過了時間上限。', 'スナップショットのダウンロードが制限時間を超えました。', '스냅샷 다운로드가 제한 시간을 초과했습니다.'],
  ['El snapshot remoto está vacío.', 'The remote snapshot is empty.', 'L’instantané distant est vide.', 'Der entfernte Snapshot ist leer.', 'O snapshot remoto está vazio.', 'L’istantanea remota è vuota.', 'Uzak anlık görüntü boş.', '远程快照为空。', '遠端快照為空。', 'リモートスナップショットが空です。', '원격 스냅샷이 비어 있습니다.'],
  ['El proceso auxiliar de réplica no está disponible. Reinstala o actualiza Nodus.', 'The replica utility process is unavailable. Reinstall or update Nodus.', 'Le processus auxiliaire de réplique est indisponible. Réinstallez ou mettez à jour Nodus.', 'Der Replikat-Hilfsprozess ist nicht verfügbar. Installieren Sie Nodus neu oder aktualisieren Sie es.', 'O processo auxiliar de réplica não está disponível. Reinstale ou atualize o Nodus.', 'Il processo ausiliario della replica non è disponibile. Reinstalla o aggiorna Nodus.', 'Kopya yardımcı işlemi kullanılamıyor. Nodus’u yeniden yükleyin veya güncelleyin.', '副本辅助进程不可用。请重新安装或更新 Nodus。', '副本輔助程序無法使用。請重新安裝或更新 Nodus。', 'レプリカの補助プロセスを利用できません。Nodus を再インストールまたは更新してください。', '복제본 보조 프로세스를 사용할 수 없습니다. Nodus를 다시 설치하거나 업데이트하세요.'],
  ['La importación del snapshot ha superado el plazo máximo de dos minutos.', 'The snapshot import exceeded its two-minute deadline.', 'L’importation de l’instantané a dépassé le délai maximal de deux minutes.', 'Der Snapshot-Import hat das Zeitlimit von zwei Minuten überschritten.', 'A importação do snapshot excedeu o prazo máximo de dois minutos.', 'L’importazione dell’istantanea ha superato il tempo massimo di due minuti.', 'Anlık görüntü içe aktarımı iki dakikalık zaman sınırını aştı.', '快照导入超过了两分钟的时间上限。', '快照匯入超過了兩分鐘的時間上限。', 'スナップショットのインポートが制限時間の 2 分を超えました。', '스냅샷 가져오기가 2분 제한 시간을 초과했습니다.'],
  ['El proceso auxiliar no devolvió un resultado.', 'The utility process did not return a result.', 'Le processus auxiliaire n’a renvoyé aucun résultat.', 'Der Hilfsprozess hat kein Ergebnis zurückgegeben.', 'O processo auxiliar não devolveu um resultado.', 'Il processo ausiliario non ha restituito un risultato.', 'Yardımcı işlem bir sonuç döndürmedi.', '辅助进程未返回结果。', '輔助程序未傳回結果。', '補助プロセスが結果を返しませんでした。', '보조 프로세스가 결과를 반환하지 않았습니다.'],
  ['La publicación se ha detenido.', 'Publication has stopped.', 'La publication a été arrêtée.', 'Die Veröffentlichung wurde gestoppt.', 'A publicação foi interrompida.', 'La pubblicazione è stata interrotta.', 'Yayımlama durduruldu.', '发布已停止。', '發佈已停止。', '公開を停止しました。', '게시가 중지되었습니다.'],
  ['Cloudflare no confirmó la página privada del inbox.', 'Cloudflare did not acknowledge the private inbox page.', 'Cloudflare n’a pas confirmé la page privée de la boîte de réception.', 'Cloudflare hat die private Posteingangsseite nicht bestätigt.', 'A Cloudflare não confirmou a página privada da caixa de entrada.', 'Cloudflare non ha confermato la pagina privata della posta in arrivo.', 'Cloudflare özel gelen kutusu sayfasını onaylamadı.', 'Cloudflare 未确认私有收件箱页面。', 'Cloudflare 未確認私人收件匣頁面。', 'Cloudflare がプライベート受信トレイのページを確認しませんでした。', 'Cloudflare가 비공개 받은 편지함 페이지를 확인하지 않았습니다.'],
  ['Cloudflare no confirmó el cursor del relay.', 'Cloudflare did not acknowledge the relay cursor.', 'Cloudflare n’a pas confirmé le curseur du relais.', 'Cloudflare hat den Relay-Cursor nicht bestätigt.', 'A Cloudflare não confirmou o cursor do relay.', 'Cloudflare non ha confermato il cursore del relay.', 'Cloudflare aktarım imlecini onaylamadı.', 'Cloudflare 未确认中继游标。', 'Cloudflare 未確認轉送游標。', 'Cloudflare がリレーのカーソルを確認しませんでした。', 'Cloudflare가 릴레이 커서를 확인하지 않았습니다.'],
  ['Cloudflare no devolvió una imagen.', 'Cloudflare did not return an image.', 'Cloudflare n’a pas renvoyé d’image.', 'Cloudflare hat kein Bild zurückgegeben.', 'A Cloudflare não devolveu uma imagem.', 'Cloudflare non ha restituito un’immagine.', 'Cloudflare bir görüntü döndürmedi.', 'Cloudflare 未返回图片。', 'Cloudflare 未傳回圖片。', 'Cloudflare が画像を返しませんでした。', 'Cloudflare가 이미지를 반환하지 않았습니다.'],
  ['La actualización Yjs supera el límite de Cloudflare de 8 MiB.', 'The Yjs update exceeds Cloudflare’s 8 MiB limit.', 'La mise à jour Yjs dépasse la limite de 8 MiB de Cloudflare.', 'Das Yjs-Update überschreitet das Cloudflare-Limit von 8 MiB.', 'A atualização Yjs excede o limite de 8 MiB da Cloudflare.', 'L’aggiornamento Yjs supera il limite di 8 MiB di Cloudflare.', 'Yjs güncellemesi Cloudflare’in 8 MiB sınırını aşıyor.', 'Yjs 更新超过 Cloudflare 的 8 MiB 上限。', 'Yjs 更新超過 Cloudflare 的 8 MiB 上限。', 'Yjs の更新が Cloudflare の上限の 8 MiB を超えています。', 'Yjs 업데이트가 Cloudflare의 8 MiB 한도를 초과합니다.'],
  ['El adjunto supera el límite de Cloudflare de 32 MiB.', 'The attachment exceeds Cloudflare’s 32 MiB limit.', 'La pièce jointe dépasse la limite de 32 MiB de Cloudflare.', 'Der Anhang überschreitet das Cloudflare-Limit von 32 MiB.', 'O anexo excede o limite de 32 MiB da Cloudflare.', 'L’allegato supera il limite di 32 MiB di Cloudflare.', 'Ek Cloudflare’in 32 MiB sınırını aşıyor.', '附件超过 Cloudflare 的 32 MiB 上限。', '附件超過 Cloudflare 的 32 MiB 上限。', '添付ファイルが Cloudflare の上限の 32 MiB を超えています。', '첨부파일이 Cloudflare의 32 MiB 한도를 초과합니다.'],
  ['La sincronización automática se ha detenido para evitar llamadas repetidas.', 'Automatic synchronization has stopped to prevent repeated requests.', 'La synchronisation automatique a été arrêtée pour éviter les requêtes répétées.', 'Die automatische Synchronisierung wurde gestoppt, um wiederholte Anfragen zu vermeiden.', 'A sincronização automática foi interrompida para evitar pedidos repetidos.', 'La sincronizzazione automatica è stata interrotta per evitare richieste ripetute.', 'Tekrarlanan istekleri önlemek için otomatik eşitleme durduruldu.', '自动同步已停止，以防止重复请求。', '自動同步已停止，以防止重複請求。', 'リクエストの繰り返しを防ぐため、自動同期を停止しました。', '반복 요청을 방지하기 위해 자동 동기화가 중지되었습니다.'],
  ['La sincronización automática se ha detenido para evitar llamadas repetidas. Vuelve a conectar o sincroniza manualmente tras resolver el error.', 'Automatic synchronization has stopped to prevent repeated requests. Reconnect or synchronize manually after resolving the error.', 'La synchronisation automatique a été arrêtée pour éviter les requêtes répétées. Reconnectez-vous ou synchronisez manuellement après avoir résolu l’erreur.', 'Die automatische Synchronisierung wurde gestoppt, um wiederholte Anfragen zu vermeiden. Verbinden Sie sich erneut oder synchronisieren Sie nach Behebung des Fehlers manuell.', 'A sincronização automática foi interrompida para evitar pedidos repetidos. Volte a ligar ou sincronize manualmente após resolver o erro.', 'La sincronizzazione automatica è stata interrotta per evitare richieste ripetute. Riconnettiti o sincronizza manualmente dopo aver risolto l’errore.', 'Tekrarlanan istekleri önlemek için otomatik eşitleme durduruldu. Hatayı giderdikten sonra yeniden bağlanın veya elle eşitleyin.', '自动同步已停止，以防止重复请求。解决错误后，请重新连接或手动同步。', '自動同步已停止，以防止重複請求。解決錯誤後，請重新連線或手動同步。', 'リクエストの繰り返しを防ぐため、自動同期を停止しました。エラーを解決してから再接続するか、手動で同期してください。', '반복 요청을 방지하기 위해 자동 동기화가 중지되었습니다. 오류를 해결한 후 다시 연결하거나 수동으로 동기화하세요.'],
  [CLOUDFLARE_SAFETY_UPGRADE_MESSAGE, 'Update the Nodus Cloud Worker and apply its migrations before synchronizing: this installation does not yet advertise cumulative limits and persistent cleanup.', 'Mettez à jour le Worker Nodus Cloud et appliquez ses migrations avant de synchroniser : cette installation n’annonce pas encore de limites cumulées ni de nettoyage persistant.', 'Aktualisieren Sie den Nodus Cloud Worker und wenden Sie seine Migrationen vor der Synchronisierung an: Diese Installation meldet noch keine kumulierten Limits und keine dauerhafte Bereinigung.', 'Atualize o Worker do Nodus Cloud e aplique as suas migrações antes de sincronizar: esta instalação ainda não anuncia limites acumulados e limpeza persistente.', 'Aggiorna il Worker di Nodus Cloud e applica le sue migrazioni prima di sincronizzare: questa installazione non dichiara ancora limiti cumulativi e pulizia persistente.', 'Eşitlemeden önce Nodus Cloud Worker’ı güncelleyin ve geçişlerini uygulayın: bu kurulum henüz birikimli sınırları ve kalıcı temizlemeyi bildirmiyor.', '同步前请更新 Nodus Cloud Worker 并应用迁移：此安装尚未声明累计限额和持久化清理。', '同步前請更新 Nodus Cloud Worker 並套用移轉：此安裝尚未宣告累計限額和持續性清理。', '同期前に Nodus Cloud Worker を更新し、マイグレーションを適用してください。この環境では累積上限と永続的なクリーンアップへの対応がまだ通知されていません。', '동기화 전에 Nodus Cloud Worker를 업데이트하고 마이그레이션을 적용하세요. 이 설치는 아직 누적 한도와 영구 정리를 지원한다고 알리지 않습니다.'],
];

function translations(row: ErrorRow, value?: string): Translations {
  const result = Object.fromEntries(languages.map((language, index) => [language,
    value === undefined ? row[index + 1] : row[index + 1].replaceAll('{value}', value)])) as Translations;
  result['pt-BR'] = result.pt;
  return result;
}

export const CLOUDFLARE_SYNC_ERRORS: Record<string, Translations> = Object.fromEntries(rows.map(row => [row[0], translations(row)]));

const patterns: [RegExp, ErrorRow][] = [
  [/^El índice (.+) supera el límite seguro de búsqueda exacta de Cloudflare\.$/, ['El índice {value} supera el límite seguro de búsqueda exacta de Cloudflare.', 'The {value} index exceeds Cloudflare’s safe exact-search limit.', 'L’index {value} dépasse la limite sûre de recherche exacte de Cloudflare.', 'Der {value}-Index überschreitet das sichere Limit für die exakte Suche von Cloudflare.', 'O índice {value} excede o limite seguro de pesquisa exata da Cloudflare.', 'L’indice {value} supera il limite sicuro di ricerca esatta di Cloudflare.', '{value} dizini Cloudflare’in güvenli tam arama sınırını aşıyor.', '{value} 索引超过 Cloudflare 的精确搜索安全上限。', '{value} 索引超過 Cloudflare 的精確搜尋安全上限。', '{value} インデックスが Cloudflare の完全一致検索の安全上限を超えています。', '{value} 인덱스가 Cloudflare의 정확 검색 안전 한도를 초과합니다.']],
  [/^El proceso auxiliar de réplica terminó sin completar la importación \((.+)\)\.$/, ['El proceso auxiliar de réplica terminó sin completar la importación ({value}).', 'The replica utility process exited without completing the import ({value}).', 'Le processus auxiliaire de réplique s’est terminé sans achever l’importation ({value}).', 'Der Replikat-Hilfsprozess wurde beendet, ohne den Import abzuschließen ({value}).', 'O processo auxiliar de réplica terminou sem concluir a importação ({value}).', 'Il processo ausiliario della replica è terminato senza completare l’importazione ({value}).', 'Kopya yardımcı işlemi içe aktarımı tamamlamadan sonlandı ({value}).', '副本辅助进程在完成导入前退出（{value}）。', '副本輔助程序在完成匯入前結束（{value}）。', 'レプリカの補助プロセスがインポートを完了せずに終了しました（{value}）。', '복제본 보조 프로세스가 가져오기를 완료하지 않고 종료되었습니다({value}).']],
  [/^No se pudieron verificar las protecciones de Cloudflare \(HTTP (\d+)\)\.$/, ['No se pudieron verificar las protecciones de Cloudflare (HTTP {value}).', 'Cloudflare safeguards could not be verified (HTTP {value}).', 'Les protections Cloudflare n’ont pas pu être vérifiées (HTTP {value}).', 'Die Cloudflare-Schutzmaßnahmen konnten nicht überprüft werden (HTTP {value}).', 'Não foi possível verificar as proteções da Cloudflare (HTTP {value}).', 'Non è stato possibile verificare le protezioni di Cloudflare (HTTP {value}).', 'Cloudflare korumaları doğrulanamadı (HTTP {value}).', '无法验证 Cloudflare 的保护措施（HTTP {value}）。', '無法驗證 Cloudflare 的保護措施（HTTP {value}）。', 'Cloudflare の保護機能を確認できませんでした（HTTP {value}）。', 'Cloudflare 보호 기능을 확인할 수 없습니다(HTTP {value}).']],
  [/^Cloudflare no devolvió el relay \(HTTP (\d+)\)\.$/, ['Cloudflare no devolvió el relay (HTTP {value}).', 'Cloudflare did not return the relay (HTTP {value}).', 'Cloudflare n’a pas renvoyé le relais (HTTP {value}).', 'Cloudflare hat das Relay nicht zurückgegeben (HTTP {value}).', 'A Cloudflare não devolveu o relay (HTTP {value}).', 'Cloudflare non ha restituito il relay (HTTP {value}).', 'Cloudflare aktarımı döndürmedi (HTTP {value}).', 'Cloudflare 未返回中继（HTTP {value}）。', 'Cloudflare 未傳回轉送資料（HTTP {value}）。', 'Cloudflare がリレーを返しませんでした（HTTP {value}）。', 'Cloudflare가 릴레이를 반환하지 않았습니다(HTTP {value}).']],
];

export const CLOUDFLARE_SYNC_ERROR_PATTERNS = patterns.map(([pattern, row]) => ({
  pattern, translate: (value: string): Translations => translations(row, value),
}));
