import type { AppSettings } from './types';
import { DEFAULT_EMBEDDING_MODELS, DEFAULT_LOCAL_BASE_URLS } from './providers';
import { NODI_ORB_DEFAULT_COLOR } from './nodiOrb';
import { NODI_DEFAULT_SCALE } from './nodiSize';
import { DEFAULT_NODUS_IMAGE_QUALITY } from './localImageModels';
import { EMPTY_CUSTOM_EVENT_TYPES } from './eventTypes';

// Factory defaults are shared by Desktop and the locally bundled mobile surfaces.
// Effective model choices and provider availability are supplied by the executing device.
export const DEFAULT_LOCAL_PROVIDERS: AppSettings['localProviders'] = {
  ollama: { baseUrl: DEFAULT_LOCAL_BASE_URLS.ollama, contextMode: 'auto' },
  lmstudio: { baseUrl: DEFAULT_LOCAL_BASE_URLS.lmstudio, contextMode: 'auto' },
};

/** No default endpoint exists for someone else's gateway: unconfigured means off. */
const DEFAULT_CUSTOM_PROVIDER: AppSettings['customProvider'] = { baseUrl: '', models: [] };

export const DEFAULT_APP_SETTINGS: Omit<AppSettings, 'providerKeys' | 'lockedProviderKeys'> = {
  // Compatibility first: a v3 settings blob has none of these keys, therefore its
  // first Nodus 4 Library visit remains the unchanged vault corpus.
  academicMode: 'auto',
  libraryGlobalEnabled: false,
  libraryScope: 'vault',
  libraryScopeOnboardingVersion: 0,
  embeddingProvider: 'openai',
  embeddingModel: DEFAULT_EMBEDDING_MODELS.openai,
  localProviders: DEFAULT_LOCAL_PROVIDERS,
  customProvider: DEFAULT_CUSTOM_PROVIDER,
  favorites: [],
  defaultModel: null,
  modelSettingsMode: 'basic',
  modelSettingsVersion: 0,
  extractionModel: null,
  visionModel: null,
  synthesisModel: null,
  summaryModel: null,
  documentProfileModel: null,
  documentAuditModel: null,
  fusionModel: null,
  relationModel: null,
  chatModel: null,
  nodiModel: null,
  deepResearchModel: null,
  immersionModel: null,
  writingModel: null,
  argumentMapModel: null,
  authorModel: null,
  dictionaryModel: null,
  studyModel: null,
  tutorModel: null,
  hypothesisModel: null,
  improveModel: null,
  studyImproveToolbarStyleIds: ['builtin:formal', 'builtin:academic', 'builtin:clear', 'builtin:concise'],
  questionGenModel: null,
  gradingModel: null,
  flashcardModel: null,
  transcriptionModel: null,
  studyAiFallbackModels: {},
  studyAiSubjectModels: {},
  studyAiMonthlyBudgetUsd: 0,
  studyAiBudgetWarningPercent: 80,
  studyAiEnabled: true,
  studyAnalyticsEnabled: true,
  studySyncEnabled: true,
  studySharingEnabled: true,
  studyAiPrivacyMode: 'hybrid',
  studyAiExcludedSubjectIds: [],
  studyAiLocalOnly: false,
  studyAiConfirmExternal: true,
  studyKnowledgeAutoProcess: 'ask',
  studentPseudonymsEnabled: true,
  studyAiMaxInputChars: 120000,
  studyAiMaxOutputTokens: 4000,
  studyAiTemperature: 0.15,
  studyAiRetryCount: 1,
  sttProvider: 'transformers',
  sttTransformersModel: 'Xenova/whisper-tiny',
  sttWhisperCppModel: 'base',
  sttWhisperCppExecutable: '',
  imageProvider: 'google',
  imageModel: 'gemini-3.1-flash-lite-image',
  imageQuality: DEFAULT_NODUS_IMAGE_QUALITY,
  imageStyle: 'antique_book',
  audioProvider: 'piper',
  audioVoice: '',
  audioSpeed: 1,
  syncMode: 'manual',
  readTag: 'leído',
  autoLightScan: false,
  autoDeepScanOnReadTag: false,
  autoSummaryAfterDeep: true,
  documentIndexingEnabled: false,
  documentIndexIncludeArchived: false,
  documentIndexConcurrency: 0,
  autoBridgeAfterQueue: true,
  autoResumeQueue: false,
  zoteroUserId: '0',
  zoteroStoragePath: '',
  monitoredCollections: [],
  theme: 'dark',
  appTheme: 'default',
  customThemes: [],
  shareAppThemeAcrossVaults: false,
  uiLanguage: 'es',
  promptLanguage: 'es',
  animationSpeed: 1,
  interfaceScale: 1,
  accessibleFont: false,
  highContrast: false,
  reduceMotion: false,
  readingFocusMode: false,
  announcementsEnabled: true,
  betaUpdates: false,
  browserSitePermissions: {},
  browserDownloadFolder: null,
  browserHomeMode: 'start',
  browserHomeUrl: '',
  browserNewTabMode: 'home',
  browserSearchEngine: 'google',
  browserSearchTemplate: '',
  browserHistoryRetention: '30d',
  browserClearHistoryOnClose: false,
  // Ten days of processing log, capped so a provider outage cannot bloat the file, and
  // rendered in English by default: the log exists to be pasted into a GitHub issue.
  pipelineLogRetention: '10d',
  pipelineLogMaxEntries: 5_000,
  pipelineLogLanguage: 'en',
  mascotEnabled: true,
  mascotScale: NODI_DEFAULT_SCALE,
  mascotAlwaysOnTop: false,
  mascotVaultCostumes: true,
  // The classic Nodi stays the default: an existing install must never wake up with a
  // different mascot. New users and upgraders are asked once, then this holds their pick.
  mascotStyle: 'classic',
  mascotStyleChosen: false,
  mascotOrbColorMode: 'auto',
  mascotOrbColor: NODI_ORB_DEFAULT_COLOR,
  aiConcurrencyMode: 'automatic',
  aiConcurrencyVersion: 1,
  concurrency: 1,
  chatReasoning: 'off',
  codexReasoningEfforts: {},
  researchEffortByModel: {},
  researchWebSearch: 'auto',
  openRouterThroughput: true,
  providerFreeTier: {},
  unpaywallEmail: '',
  onboardingComplete: false,
  basicsTutorialVersion: 0,
  firstVaultVersion: 0,
  tutorialVideosWatched: [],
  tourComplete: false,
  advancedTourComplete: true,
  demoMode: false,
  demoPriorVaultType: null,
  customEventTypes: EMPTY_CUSTOM_EVENT_TYPES,
  genealogyTourComplete: false,
  databasesTourComplete: false,
  testimonyTourComplete: false,
  studyTourComplete: false,
  docenciaTourComplete: false,
  primarySourcesTourComplete: false,
  primarySourcesLocalMetricsEnabled: false,
  preferZoteroFulltext: true,
  ocrEnabled: false,
  ocrLanguages: 'spa+eng',
  ocrMaxPages: 300,
  declutterNewDocuments: true,
  chemistryUseStockLists: true,
  toolkitOcrLanguages: 'spa+eng',
  toolkitOutputDir: null,
  toolkitOpenFolderOnDone: false,
  deepContextMode: 'standard',
  deepStandardChunkWords: 1800,
  deepLongChunkWords: 30000,
  themesLocked: false,
  mcpEnabled: false,
  mcpPort: 4319,
  mcpToken: '',
  nodusServerEnabled: false,
  nodusServerKind: 'classic',
  nodusServerUrl: '',
  nodusServerSpaceId: '',
  nodusServerSpaceName: '',
  nodusServerLanguage: 'en',
  nodusServerIncludeUserContent: false,
  nodusServerIncludePassages: false,
  nodusServerIncludePrimarySources: false,
  nodusServerIncludeTestimonies: false,
  nodusServerIncludeLibraryDocuments: false,
  nodusServerIncludeVectors: true,
  nodusServerAutoSync: true,
  localServerEnabled: false,
  localServerPort: 7443,
  localServerAccess: 'loopback',
  localServerAdminEmail: '',
  localServerKeepAwake: false,
  localServerKeepServingOnLidClose: false,
  copilotEnabled: false,
  copilotPort: 4320,
  copilotToken: '',
  zoteroPluginEnabled: false,
  zoteroPluginPort: 4321,
  zoteroPluginToken: '',
  browserConnectorEnabled: false,
  browserConnectorToken: '',
  browserConnectorOrigin: '',
  sidebarOrder: [],
  sidebarHidden: [],
  sidebarCustomized: false,
  scriptorSidebarVersion: 1,
  // A new profile starts with Nodus Drift pinned, the way Nodus Browser is in the sidebar. A profile that
  // already saved its pins keeps them: this is only where a profile with none starts from.
  toolkitPinnedPages: ['drift'],
  treeFrame: 'oak',
  treeFocusPersonId: null,
  treeOrientation: 'ancestors_top',
  treePaternalColor: '#2563eb',
  treeMaternalColor: '#dc2626',
  treePaternalBranchVisible: true,
  treeMaternalBranchVisible: true,
  recoverySetupVersion: 0,
  backupVaultIds: [],
  backupIncludePreferences: true,
  backupIncludeHistories: true,
  backupIncludeGeneratedMedia: true,
  backupIncludeApiKeys: true,
  testimonyDefaultLanguage: '',
  testimonyDefaultAccess: 'private',
  testimonyDefaultAttribution: 'public_name',
  testimonyNarratorReviewDefault: false,
  testimonyRepositoryName: '',
  testimonyRetentionPolicy: '',
  testimonyAgreementTemplate: '',
  testimonyAllowExternalProviders: false,
  testimonyProjectPurpose: '',
  autoBackupEnabled: false,
  autoBackupFolder: '',
  autoBackupIntervalHours: 24,
  autoBackupDays: [],
  autoBackupHour: 3,
  autoBackupMinute: 0,
  lastAutoBackupAt: null,
  lastAutoBackupStatus: null,
  backupCleanupEnabled: false,
  backupRetentionValue: 3,
  backupRetentionUnit: 'months',
  lastBackupCleanupAt: null,
  lastBackupCleanupStatus: null,
};
