/** Closed operation vocabulary. Browser, tools, extraction and indexers have no mobile route. */
export const MOBILE_OPERATIONS = {
  getWork: ['works:get', 'corpus'],
  getThemes: ['graph:themes', 'corpus'],
  getIdeasByWork: ['works:ideasByWork', 'corpus'],
  getIdeaEdges: ['graph:ideaEdges', 'corpus'],
  getAuthorDossier: ['authors:dossier', 'corpus'],
  getWorkIdeaSynthesis: ['works:getIdeaSynthesis', 'corpus'],
  getWorkSummary: ['works:getSummary', 'corpus'],
  getGapDetail: ['gaps:detail', 'corpus'],
  getGlobalLibraryItem: ['library:item', 'corpus'],
  getLibraryReaderDocument: ['libraryReader:get', 'corpus'],
  getResearchCorpusSources: ['research:corpus:sources', 'corpus'],
  getResearchPreparationInventory: ['research:preparation:inventory', 'corpus'],
  getCompleteGuideEvidence: ['research:completeGuide:evidence', 'corpus'],
  listCompleteGuideCatalog: ['research:completeGuide:catalog', 'corpus'],
  previewCompleteGuide: ['research:completeGuide:preview', 'corpus'],
  listStudyMaterials: ['study:materials:list', 'corpus'],
  listStudyIdeas: ['study:knowledge:ideas', 'corpus'],
  getStudyIdeaDetail: ['study:knowledge:idea', 'corpus'],
  getStudyKnowledgeGraph: ['study:knowledge:graph', 'corpus'],
  getStudyDocEditorData: ['study:editor:data', 'corpus'],
  listImageModels: ['ai:listImageModels', 'corpus'],
  getAppInfo: ['app:info', 'corpus'],
  getDocumentVisuals: ['documentVisuals:get', 'corpus'],
  getSettings: ['settings:get', 'corpus'],
  listAudioClips: ['audio:listClips', 'corpus'],
  exportWritingWorkshopDraft: ['mobile:export:writing', 'corpus'], exportDeepResearchArchive: ['mobile:export:archive', 'corpus'],
  exportImmersionSessionPdf: ['mobile:export:immersion', 'corpus'],
  listPickerIdeas: ['ideas:picker', 'corpus'],
  updateSettings: ['settings:update', 'research-generation'],
  getGraph: ['graph:get', 'corpus'], stellarPage: ['stellar:page', 'corpus'], stellarThemes: ['stellar:themes', 'corpus'],
  getIdeaDetail: ['graph:ideaDetail', 'corpus'], getEdgeDetail: ['graph:edgeDetail', 'corpus'], getWorkMeta: ['works:meta', 'corpus'],
  listAuthors: ['authors:list', 'corpus'], listWorks: ['works:list', 'corpus'], listWorksPage: ['works:listPage', 'corpus'],
  listCollectionFacets: ['works:collectionFacets', 'corpus'], listZoteroTags: ['works:listZoteroTags', 'corpus'],
  listDictionaryEntries: ['dictionary:list', 'corpus'], listDictionaryFacets: ['dictionary:facets', 'corpus'],
  getDictionaryGenerationContext: ['dictionary:mobile:context', 'corpus'],
  scanDictionaryMobileEvidence: ['dictionary:mobile:scan', 'writing'],
  saveDictionaryGeneratedVersion: ['dictionary:mobile:save', 'writing'],
  getDictionaryEntry: ['dictionary:get', 'corpus'], listDictionaryEvidence: ['dictionary:evidence:list', 'corpus'],
  listDictionaryVersions: ['dictionary:versions:list', 'corpus'], listDictionaryGenerationJobs: ['dictionary:generate:jobs', 'corpus'],
  createDictionaryEntry: ['dictionary:create', 'writing'], updateDictionaryEntry: ['dictionary:update', 'writing'],
  setDictionaryEvidenceDecision: ['dictionary:evidence:decision', 'writing'],
  addDictionaryRelation: ['dictionary:relations:add', 'writing'], acceptDictionaryVersion: ['dictionary:versions:accept', 'writing'],
  restoreDictionaryVersion: ['dictionary:versions:restore', 'writing'], startDictionaryGeneration: ['dictionary:generate:mobile', 'research-generation'],
  deleteDictionaryEntries: ['dictionary:delete', 'writing'],
  scanDictionaryNewEvidence: ['dictionary:scan', 'research-generation'], detectDictionaryDuplicates: ['dictionary:duplicates', 'corpus'],
  getNotesTree: ['notes:tree', 'corpus'], getWorkspaceNoteEditorData: ['workspace:editor:data', 'corpus'],
  listEditorReferences: ['editor:references', 'corpus'], getStudyWorkspace: ['study:workspace', 'corpus'],
  listAllWorkspaceLibraryLinks: ['workspace:library:all', 'corpus'], listStudyNoteLinks: ['study:noteLinks:list', 'corpus'],
  listStudyStyles: ['study:styles:list', 'corpus'], getPassage: ['passages:get', 'corpus'],
  listStudyStyleVersions: ['study:styles:versions', 'corpus'], listStudyStyleAssociations: ['study:styles:associations', 'corpus'],
  resolveStudyStyleDefault: ['study:styles:default', 'corpus'], listStudyImprovementLog: ['study:improve:log', 'corpus'],
  createStudyStyle: ['study:styles:create', 'writing'], updateStudyStyle: ['study:styles:update', 'writing'],
  duplicateStudyStyle: ['study:styles:duplicate', 'writing'], archiveStudyStyle: ['study:styles:archive', 'writing'],
  deleteStudyStyle: ['study:styles:delete', 'writing'], restoreStudyStyleVersion: ['study:styles:restore', 'writing'],
  setStudyStyleAssociation: ['study:styles:associate', 'writing'], updateStudyImprovementAction: ['study:improve:action', 'writing'],
  getStudyImprovementGenerationContext: ['study:improve:mobile:context', 'corpus'],
  saveStudyImprovementFromMobile: ['study:improve:mobile:save', 'writing'],
  createNote: ['notes:create', 'writing'], updateWorkspaceNote: ['workspace:editor:update', 'writing'],
  createManualIdea: ['manualIdeas:create', 'writing'], deleteNotesPermanently: ['notes:deletePermanently', 'writing'],
  saveManualIdea: ['manualIdeas:save', 'writing'], getManualIndexStatus: ['manualIdeas:indexStatus', 'corpus'], searchIdeaCandidates: ['manualIdeas:searchCandidates', 'corpus'],
  saveResearchNotebook: ['research:notebooks:save-mobile', 'writing'],
  getResearchNotebookPreparation: ['research:notebooks:preparation-read', 'corpus'], deleteResearchNotebook: ['research:notebooks:delete', 'writing'],
  getCitationPreview: ['citations:preview', 'corpus'], verifyCitations: ['citations:verify', 'corpus'],
  listGlobalLibraryItems: ['library:list', 'corpus'],
  createNoteFolder: ['notes:folders:create', 'writing'], renameNoteFolder: ['notes:folders:rename', 'writing'],
  moveNote: ['notes:move', 'writing'], patchNoteTags: ['notes:tags:patch', 'writing'],
  trashNoteFolder: ['notes:folders:trash', 'writing'], removeStudyNoteLinks: ['study:noteLinks:remove', 'writing'],
  trashNotes: ['notes:trash', 'writing'], restoreNotes: ['notes:restore', 'writing'],
  restoreWorkspaceNoteVersion: ['workspace:editor:restore', 'writing'],
  createWorkspaceAnnotation: ['workspace:annotation:create', 'writing'], updateWorkspaceAnnotation: ['workspace:annotation:update', 'writing'],
  addWorkspaceLibraryLink: ['workspace:library:add', 'writing'], removeWorkspaceLibraryLink: ['workspace:library:remove', 'writing'],
  listModels: ['ai:listModels', 'corpus'], getModelCatalog: ['ai:modelCatalog', 'corpus'],
  discoverArgumentRoutes: ['argumentMap:discover', 'corpus'], buildArgumentMap: ['argumentMap:build', 'research-generation'],
  listWritingWorkshopDrafts: ['writing:saved:list', 'corpus'],
  listDeepResearchJobs: ['research:deep:queue:list', 'corpus'], enqueueDeepResearchJob: ['research:deep:queue:enqueue-mobile', 'research-generation'],
  clearFinishedDeepResearchJobs: ['research:deep:queue:clear-mobile', 'research-generation'],
  cancelDeepResearchJob: ['research:deep:queue:cancel', 'research-generation'],
  listPersons: ['entities:listPersons', 'corpus'],
  getContentTranslation: ['translations:get', 'corpus'],
  listContentTranslations: ['translations:list', 'corpus'], generateContentTranslation: ['translations:generate', 'research-generation'],
  deleteContentTranslation: ['translations:delete', 'writing'],
  getContentTranslationGenerationContext: ['translations:mobile:context', 'corpus'],
  beginContentTranslationOnMobile: ['translations:mobile:begin', 'writing'],
  saveContentTranslationFromMobile: ['translations:mobile:save', 'writing'],
  failContentTranslationOnMobile: ['translations:mobile:fail', 'writing'],
  listWritingDraftAnnotations: ['writing:annotations:list', 'corpus'],
  createWritingDraftAnnotation: ['writing:annotations:create', 'writing'],
  updateWritingDraftComment: ['writing:annotations:updateComment', 'writing'],
  deleteWritingDraftAnnotation: ['writing:annotations:delete', 'writing'],
  deleteWritingWorkshopDraft: ['writing:saved:delete', 'writing'],
  setWritingWorkshopDraftRead: ['writing:saved:read', 'writing'],
  buildImmersionScope: ['immersion:scope', 'corpus'], listImmersionSessions: ['immersion:list', 'corpus'],
  getImmersionSession: ['immersion:get', 'corpus'], restartImmersionSession: ['immersion:restart', 'writing'],
  setImmersionProgress: ['immersion:progress:set', 'writing'], answerImmersionQuestion: ['immersion:answer', 'writing'],
  generateImmersionSession: ['immersion:generate', 'research-generation'], deleteImmersionSession: ['immersion:delete', 'writing'],
  getImmersionGenerationContext: ['immersion:mobile:context', 'corpus'], saveImmersionGeneratedSession: ['immersion:mobile:save', 'writing'],
  getWritingWorkshopSnapshot: ['writing:snapshot', 'corpus'], generateWritingWorkshopDraft: ['writing:draft', 'research-generation'],
  researchChat: ['research:chat', 'research-generation'], researchChatStream: ['research:chatStream', 'research-generation'],
  improveStudyText: ['study:improve', 'research-generation'], suggestStudySynonyms: ['study:synonyms', 'research-generation'],
  getDecorativeImage: ['images:get', 'corpus'], getDecorativeImageDataUrl: ['images:data', 'corpus'],
  listDocumentSkills: ['documentSkills:list', 'corpus'],
  listConversations: ['chat:list', 'corpus'], getConversation: ['chat:get', 'corpus'],
  createConversation: ['chat:create', 'writing'], saveConversationMessages: ['chat:saveMessages', 'writing'],
  renameConversation: ['chat:rename', 'writing'], archiveConversation: ['chat:archive', 'writing'], deleteConversation: ['chat:delete', 'writing'],
  generateConversationTitle: ['chat:generateTitle', 'research-generation'],
  listChatProjects: ['chat:projects:list', 'corpus'], createChatProject: ['chat:projects:create', 'writing'],
  updateChatProject: ['chat:projects:update', 'writing'], deleteChatProject: ['chat:projects:delete', 'writing'],
  listChatProjectFolders: ['chat:folders:list', 'corpus'], createChatProjectFolder: ['chat:folders:create', 'writing'],
  renameChatProjectFolder: ['chat:folders:rename', 'writing'], moveChatProjectFolder: ['chat:folders:move', 'writing'],
  deleteChatProjectFolder: ['chat:folders:delete', 'writing'], setConversationProject: ['chat:setProject', 'writing'],
  setConversationFolder: ['chat:setFolder', 'writing'], setConversationPinned: ['chat:setPinned', 'writing'],
  getResearchSystemPrompts: ['research:prompts:list', 'corpus'], saveResearchSystemPrompt: ['research:prompts:save', 'writing'],
  selectResearchSystemPrompt: ['research:prompts:select', 'writing'], deleteResearchSystemPrompt: ['research:prompts:delete', 'writing'],
  listResearchContextSources: ['research:contextSources', 'corpus'], listResearchAttachments: ['research:attachments:list', 'corpus'],
  listResearchNotebooks: ['research:notebooks:list', 'corpus'], resolveResearchNotebook: ['research:notebooks:resolve', 'corpus'],
  updateResearchNotebookAppearance: ['research:notebooks:appearance', 'writing'],
} as const;
export type MobileOperation = keyof typeof MOBILE_OPERATIONS;
export const MOBILE_JOB_OPERATIONS: ReadonlySet<string> = new Set([
  'exportWritingWorkshopDraft', 'exportDeepResearchArchive', 'exportImmersionSessionPdf',
  'saveDictionaryGeneratedVersion', 'saveImmersionGeneratedSession', 'saveContentTranslationFromMobile', 'saveStudyImprovementFromMobile', 'startDictionaryGeneration', 'enqueueDeepResearchJob',
  'generateImmersionSession', 'generateWritingWorkshopDraft', 'generateContentTranslation',
  'researchChat', 'researchChatStream', 'improveStudyText', 'buildArgumentMap', 'scanDictionaryNewEvidence', 'generateConversationTitle',
]);
