// SPDX-FileCopyrightText: 2026 Jorge Pérez Burgueño and Nodus contributors
// SPDX-License-Identifier: AGPL-3.0-only
import type { CategorizedReleaseHighlight } from './releaseNotes';

/** Final changes since v5.8.0. Scriptor is presented as new for this release. */
export const RELEASE_5_8_1_HIGHLIGHTS: CategorizedReleaseHighlight[] = [
  {
    category: 'new', scope: 'toolkit',
    es: 'Nodus Scriptor, en Herramientas, permite escribir y organizar documentos con texto enriquecido, tablas, imágenes y fórmulas. Inserta fuentes e ideas con [[, añade citas, bibliografía y notas, reúne capítulos y exporta a Word, PDF o LaTeX. Incluye historial de versiones, escritura a pantalla completa y mejoras de texto con IA que puedes cancelar o deshacer. Disponible en escritorio y en la web del servidor.',
    en: 'Nodus Scriptor, in Tools, lets you write and organize documents with rich text, tables, images and formulas. Insert sources and ideas with [[, add citations, bibliographies and notes, assemble chapters and export to Word, PDF or LaTeX. It includes version history, fullscreen writing and AI text improvements that you can cancel or undo. Available on Desktop and Server web.',
    fr: 'Nodus Scriptor, dans Outils, permet de rédiger et d’organiser des documents avec du texte enrichi, des tableaux, des images et des formules. Insérez des sources et des idées avec [[, ajoutez citations, bibliographie et notes, assemblez des chapitres et exportez vers Word, PDF ou LaTeX. Il comprend un historique des versions, la rédaction en plein écran et des améliorations du texte par IA que vous pouvez interrompre ou annuler. Disponible sur ordinateur et sur le web du serveur.',
    de: 'Mit Nodus Scriptor unter Werkzeuge schreiben und organisieren Sie Dokumente mit formatiertem Text, Tabellen, Bildern und Formeln. Fügen Sie Quellen und Ideen mit [[ ein, ergänzen Sie Zitate, Literaturverzeichnisse und Anmerkungen, stellen Sie Kapitel zusammen und exportieren Sie nach Word, PDF oder LaTeX. Enthalten sind Versionsverlauf, Schreiben im Vollbild und KI-Textverbesserungen, die Sie abbrechen oder rückgängig machen können. Verfügbar auf dem Desktop und im Server-Webzugang.',
    pt: 'O Nodus Scriptor, em Ferramentas, permite escrever e organizar documentos com texto formatado, tabelas, imagens e fórmulas. Insira fontes e ideias com [[, acrescente citações, bibliografia e notas, reúna capítulos e exporte para Word, PDF ou LaTeX. Inclui histórico de versões, escrita em ecrã inteiro e melhorias de texto com IA que pode cancelar ou desfazer. Disponível no computador e na web do servidor.',
    'pt-BR': 'O Nodus Scriptor, em Ferramentas, permite escrever e organizar documentos com texto formatado, tabelas, imagens e fórmulas. Insira fontes e ideias com [[, adicione citações, bibliografia e notas, reúna capítulos e exporte para Word, PDF ou LaTeX. Inclui histórico de versões, escrita em tela cheia e melhorias de texto com IA que você pode cancelar ou desfazer. Disponível no desktop e na web do servidor.',
    it: 'Nodus Scriptor, in Strumenti, permette di scrivere e organizzare documenti con testo formattato, tabelle, immagini e formule. Inserisci fonti e idee con [[, aggiungi citazioni, bibliografie e note, riunisci capitoli ed esporta in Word, PDF o LaTeX. Include cronologia delle versioni, scrittura a schermo intero e miglioramenti del testo con IA che puoi interrompere o annullare. Disponibile sul desktop e sul web del server.',
    tr: 'Araçlar içindeki Nodus Scriptor, biçimlendirilmiş metin, tablo, görsel ve formüllerle belge yazmanızı ve düzenlemenizi sağlar. [[ ile kaynak ve fikir ekleyebilir, atıf, kaynakça ve not oluşturabilir, bölümleri birleştirip Word, PDF veya LaTeX olarak dışa aktarabilirsiniz. Sürüm geçmişi, tam ekran yazma ve iptal edebileceğiniz veya geri alabileceğiniz yapay zekâ metin iyileştirmeleri içerir. Masaüstünde ve sunucunun web arayüzünde kullanılabilir.',
    'zh-CN': '工具中的 Nodus Scriptor 可编写和整理包含富文本、表格、图片和公式的文档。输入 [[ 可插入来源和观点，还可添加引文、参考文献和注释，组合章节并导出为 Word、PDF 或 LaTeX。支持版本历史、全屏写作，以及可取消或撤销的 AI 文本修改。桌面端和服务器网页端均可使用。',
    'zh-TW': '工具中的 Nodus Scriptor 可撰寫和整理包含格式化文字、表格、圖片和公式的文件。輸入 [[ 可插入來源和觀點，亦可加入引文、參考文獻和註釋，組合章節並匯出為 Word、PDF 或 LaTeX。支援版本歷程、全螢幕寫作，以及可取消或復原的 AI 文字修改。桌面版和伺服器網頁版均可使用。',
    ja: 'ツールのNodus Scriptorで、書式付きテキスト、表、画像、数式を含む文書を作成して整理できます。[[ で資料やアイデアを挿入し、引用、参考文献、注を追加し、章をまとめてWord、PDF、LaTeXに書き出せます。バージョン履歴、全画面での執筆、中止や取り消しができるAIの文章改善も使えます。デスクトップとサーバーのWeb画面で利用できます。',
    ko: '도구의 Nodus Scriptor에서 서식 있는 텍스트, 표, 이미지, 수식으로 문서를 작성하고 정리할 수 있습니다. [[ 로 자료와 아이디어를 삽입하고, 인용, 참고문헌, 주석을 추가하며, 장을 모아 Word, PDF 또는 LaTeX로 내보낼 수 있습니다. 버전 기록, 전체 화면 작성, 취소하거나 되돌릴 수 있는 AI 텍스트 개선을 제공합니다. 데스크톱과 서버 웹에서 사용할 수 있습니다.',
  },
  {
    category: 'enhancement', scope: 'ai',
    es: 'Las plantillas de Chemistry Studio consideran los reactivos de cada esquema. La preparación de los índices valida el mapeo de átomos y permite excluir esquemas con problemas de mecanismo o estereoquímica.',
    en: 'Chemistry Studio templates take each scheme’s reagents into account. Index preparation validates atom mapping and lets you exclude schemes with mechanism or stereochemistry problems.',
    fr: 'Les modèles de Chemistry Studio tiennent compte des réactifs de chaque schéma. La préparation des index valide la correspondance des atomes et permet d’exclure les schémas présentant des problèmes de mécanisme ou de stéréochimie.',
    de: 'Vorlagen von Chemistry Studio berücksichtigen die Reagenzien jedes Schemas. Die Indexerstellung prüft die Atomzuordnung und ermöglicht es, Schemata mit Problemen im Mechanismus oder in der Stereochemie auszuschließen.',
    pt: 'As regras de reação do Chemistry Studio consideram os reagentes de cada esquema. A preparação dos índices valida o mapeamento dos átomos e permite excluir esquemas com problemas de mecanismo ou estereoquímica.',
    'pt-BR': 'As regras de reação do Chemistry Studio consideram os reagentes de cada esquema. A preparação dos índices valida o mapeamento dos átomos e permite excluir esquemas com problemas de mecanismo ou estereoquímica.',
    it: 'I modelli di Chemistry Studio tengono conto dei reagenti di ogni schema. La preparazione degli indici verifica la corrispondenza degli atomi e permette di escludere schemi con problemi di meccanismo o stereochimica.',
    tr: 'Chemistry Studio şablonları her şemanın reaktiflerini dikkate alır. İndeks hazırlama, atom eşlemesini doğrular ve mekanizma veya stereokimya sorunları olan şemaları dışlamanıza olanak tanır.',
    'zh-CN': 'Chemistry Studio 模板会考虑每个反应图式中的试剂。建立索引时会验证原子映射，并可排除存在反应机理或立体化学问题的图式。',
    'zh-TW': 'Chemistry Studio 範本會考慮每個反應圖式中的試劑。建立索引時會驗證原子映射，並可排除存在反應機構或立體化學問題的圖式。',
    ja: 'Chemistry Studioのテンプレートは各反応図式の試薬を考慮します。インデックス作成時に原子マッピングを検証し、反応機構や立体化学に問題がある図式を除外できます。',
    ko: 'Chemistry Studio 템플릿은 각 반응 도식의 시약을 고려합니다. 인덱스를 만들 때 원자 매핑을 검증하며 반응 메커니즘이나 입체화학에 문제가 있는 도식을 제외할 수 있습니다.',
  },
  {
    category: 'enhancement', scope: 'academic',
    es: 'Research Chat ajusta la longitud de sus respuestas al espacio disponible y a los límites del modelo. Esto permite respuestas y rutas de síntesis más largas en los modelos compatibles, con menos interrupciones por el límite de salida.',
    en: 'Research Chat adjusts response length to the available context space and the model’s limits. Supported models can produce longer answers and synthesis routes with fewer interruptions caused by the output limit.',
    fr: 'Research Chat adapte la longueur des réponses à l’espace de contexte disponible et aux limites du modèle. Les modèles compatibles peuvent produire des réponses et des voies de synthèse plus longues, avec moins d’interruptions dues à la limite de sortie.',
    de: 'Research Chat passt die Antwortlänge an den verfügbaren Kontext und die Modellgrenzen an. Unterstützte Modelle können längere Antworten und Syntheserouten erzeugen, die seltener durch das Ausgabelimit unterbrochen werden.',
    pt: 'O Research Chat ajusta a extensão das respostas ao espaço de contexto disponível e aos limites do modelo. Os modelos compatíveis podem produzir respostas e rotas de síntese mais longas, com menos interrupções devido ao limite de saída.',
    'pt-BR': 'O Research Chat ajusta o tamanho das respostas ao espaço de contexto disponível e aos limites do modelo. Os modelos compatíveis podem produzir respostas e rotas de síntese mais longas, com menos interrupções devido ao limite de saída.',
    it: 'Research Chat adatta la lunghezza delle risposte allo spazio di contesto disponibile e ai limiti del modello. I modelli compatibili possono produrre risposte e percorsi di sintesi più lunghi, con meno interruzioni dovute al limite di output.',
    tr: 'Research Chat, yanıt uzunluğunu kullanılabilir bağlam alanına ve modelin sınırlarına göre ayarlar. Desteklenen modeller daha uzun yanıtlar ve sentez yolları üretebilir ve çıktı sınırı nedeniyle daha az kesinti yaşanır.',
    'zh-CN': 'Research Chat 会根据可用上下文空间和模型限制调整回答长度。支持的模型可以生成更长的回答和合成路线，减少因输出限制而中断的情况。',
    'zh-TW': 'Research Chat 會根據可用的上下文空間和模型限制調整回答長度。支援的模型可以產生更長的回答和合成路線，減少因輸出限制而中斷的情況。',
    ja: 'Research Chatは利用可能なコンテキスト領域とモデルの上限に合わせて回答の長さを調整します。対応モデルでは、出力上限による中断を減らし、より長い回答や合成経路を生成できます。',
    ko: 'Research Chat이 사용 가능한 컨텍스트 공간과 모델 제한에 맞춰 답변 길이를 조정합니다. 지원되는 모델은 출력 제한으로 인한 중단을 줄이고 더 긴 답변과 합성 경로를 생성할 수 있습니다.',
  },
  {
    category: 'fix', scope: 'ai',
    es: 'La comprobación de rutas de síntesis usa las sustancias declaradas en el texto y conserva los componentes repetidos de las sales. Distingue los pasos que no pudo comprobar y muestra el origen de las estructuras. El diagrama de la ruta solo se genera cuando esta supera la comprobación.',
    en: 'Synthesis route checks use the substances declared in the text and retain repeated salt components. They identify steps that could not be checked and show where structures came from. A route diagram is generated only when the route passes its checks.',
    fr: 'La vérification des voies de synthèse utilise les substances déclarées dans le texte et conserve les composants répétés des sels. Elle distingue les étapes qui n’ont pas pu être vérifiées et indique l’origine des structures. Le diagramme est généré uniquement si la voie réussit les vérifications.',
    de: 'Die Prüfung von Syntheserouten verwendet die im Text angegebenen Stoffe und erhält wiederholte Salzbestandteile. Sie kennzeichnet Schritte, die nicht geprüft werden konnten, und zeigt die Herkunft der Strukturen. Ein Routendiagramm wird nur erstellt, wenn die Route die Prüfungen besteht.',
    pt: 'A verificação de rotas de síntese usa as substâncias declaradas no texto e preserva os componentes repetidos dos sais. Identifica as etapas que não puderam ser verificadas e mostra a origem das estruturas. O diagrama só é gerado quando a rota passa nas verificações.',
    'pt-BR': 'A verificação de rotas de síntese usa as substâncias declaradas no texto e preserva os componentes repetidos dos sais. Identifica as etapas que não puderam ser verificadas e mostra a origem das estruturas. O diagrama só é gerado quando a rota passa nas verificações.',
    it: 'La verifica dei percorsi di sintesi usa le sostanze dichiarate nel testo e conserva i componenti ripetuti dei sali. Distingue i passaggi che non è stato possibile verificare e mostra l’origine delle strutture. Il diagramma viene generato solo se il percorso supera le verifiche.',
    tr: 'Sentez yolu denetimleri metinde belirtilen maddeleri kullanır ve tuzların tekrarlanan bileşenlerini korur. Denetlenemeyen adımları belirtir ve yapıların kaynağını gösterir. Yol diyagramı yalnızca yol denetimleri geçtiğinde oluşturulur.',
    'zh-CN': '合成路线检查使用文本中声明的物质，并保留盐中重复的组分。检查会标明无法验证的步骤，并显示结构的来源。只有路线通过检查后，才会生成路线图。',
    'zh-TW': '合成路線檢查使用文字中聲明的物質，並保留鹽中重複的組分。檢查會標示無法驗證的步驟，並顯示結構的來源。只有路線通過檢查後，才會產生路線圖。',
    ja: '合成経路の検証は文章で明示された物質を使い、塩の重複する成分を保持します。検証できなかったステップを区別し、構造の出典を表示します。経路図は経路が検証に合格した場合にのみ生成されます。',
    ko: '합성 경로 검증은 텍스트에 명시된 물질을 사용하고 염의 반복된 구성 성분을 유지합니다. 검증할 수 없었던 단계를 구분하고 구조의 출처를 표시합니다. 경로가 검증을 통과한 경우에만 경로 다이어그램을 생성합니다.',
  },
  {
    category: 'fix', scope: 'ai',
    es: 'Los resultados guardados por los plugins registran la versión del contenido que los produjo. Sustituir un paquete instalado ya no hace que el resultado indique una versión anterior del plugin.',
    en: 'Results saved by plugins record the version of the content that produced them. Replacing an installed package no longer makes a result report an older plugin version.',
    fr: 'Les résultats enregistrés par les plugins indiquent la version du contenu qui les a produits. Remplacer un paquet installé ne fait plus apparaître une ancienne version du plugin dans le résultat.',
    de: 'Von Plugins gespeicherte Ergebnisse erfassen die Version des Inhalts, der sie erzeugt hat. Nach dem Ersetzen eines installierten Pakets zeigt das Ergebnis keine ältere Plugin-Version mehr an.',
    pt: 'Os resultados guardados pelos plugins registam a versão do conteúdo que os produziu. Substituir um pacote instalado já não faz com que o resultado indique uma versão anterior do plugin.',
    'pt-BR': 'Os resultados salvos pelos plugins registram a versão do conteúdo que os produziu. Substituir um pacote instalado já não faz o resultado indicar uma versão anterior do plugin.',
    it: 'I risultati salvati dai plugin registrano la versione del contenuto che li ha prodotti. La sostituzione di un pacchetto installato non fa più indicare al risultato una versione precedente del plugin.',
    tr: 'Eklentilerin kaydettiği sonuçlar, onları üreten içeriğin sürümünü kaydeder. Kurulu bir paket değiştirildiğinde sonuç artık eski bir eklenti sürümünü göstermez.',
    'zh-CN': '插件保存的结果会记录生成它们的内容版本。替换已安装的插件包后，结果不再显示旧的插件版本。',
    'zh-TW': '外掛儲存的結果會記錄產生它們的內容版本。替換已安裝的外掛套件後，結果不再顯示舊的外掛版本。',
    ja: 'プラグインが保存する結果には、その結果を生成した内容のバージョンが記録されます。インストール済みパッケージを置き換えても、結果に以前のプラグインバージョンが表示されなくなりました。',
    ko: '플러그인이 저장한 결과에 해당 결과를 생성한 콘텐츠의 버전을 기록합니다. 설치된 패키지를 교체한 뒤 결과에 이전 플러그인 버전이 표시되는 문제를 수정했습니다.',
  },
  {
    category: 'fix', scope: 'academic',
    es: 'Research Chat vuelve a recuperar pasajes en bibliotecas grandes y con instrucciones extensas. Las citas guardadas siguen resolviéndose y las nuevas no se bloquean al alcanzar el límite anterior. El contexto incluye las obras que participaron en la consulta, sin añadir títulos ajenos a ella.',
    en: 'Research Chat retrieves passages correctly in large libraries and with lengthy instructions. Saved citations keep resolving and new citations are no longer blocked by the previous limit. The context includes works that contributed to the query without adding unrelated titles.',
    fr: 'Research Chat retrouve les passages dans les grandes bibliothèques et avec des instructions longues. Les citations enregistrées restent accessibles et les nouvelles ne sont plus bloquées par l’ancienne limite. Le contexte inclut les œuvres ayant contribué à la recherche sans ajouter de titres sans rapport.',
    de: 'Research Chat ruft Passagen in großen Bibliotheken und bei langen Anweisungen wieder korrekt ab. Gespeicherte Zitate bleiben aufrufbar und neue Zitate werden nicht mehr durch das frühere Limit blockiert. Der Kontext enthält Werke, die zur Anfrage beigetragen haben, ohne unbeteiligte Titel hinzuzufügen.',
    pt: 'O Research Chat volta a recuperar passagens em bibliotecas grandes e com instruções extensas. As citações guardadas continuam acessíveis e as novas já não são bloqueadas pelo limite anterior. O contexto inclui as obras que contribuíram para a consulta, sem acrescentar títulos alheios a ela.',
    'pt-BR': 'O Research Chat volta a recuperar trechos em bibliotecas grandes e com instruções extensas. As citações salvas continuam acessíveis e as novas não são mais bloqueadas pelo limite anterior. O contexto inclui as obras que contribuíram para a consulta, sem acrescentar títulos sem relação com ela.',
    it: 'Research Chat recupera correttamente i passaggi nelle biblioteche grandi e con istruzioni lunghe. Le citazioni salvate restano accessibili e le nuove non sono più bloccate dal limite precedente. Il contesto include le opere che hanno contribuito alla ricerca, senza aggiungere titoli estranei.',
    tr: 'Research Chat, büyük kütüphanelerde ve uzun talimatlarla pasajları yeniden doğru şekilde getirir. Kaydedilmiş atıflar açılmaya devam eder ve yeni atıflar önceki sınır nedeniyle engellenmez. Bağlam, sorguya katkıda bulunan eserleri içerir ve ilgisiz başlıklar eklemez.',
    'zh-CN': 'Research Chat 在大型文献库和较长指令下能正确检索段落。已保存的引文仍可定位原文，新引文不再受旧数量上限阻挡。上下文包含参与查询的文献，不再添加无关标题。',
    'zh-TW': 'Research Chat 在大型文獻庫和較長指令下能正確檢索段落。已儲存的引文仍可定位原文，新引文不再受舊數量上限阻擋。上下文包含參與查詢的文獻，不再加入無關標題。',
    ja: 'Research Chatが大規模なライブラリや長い指示でも資料の該当箇所を正しく取得できるようになりました。保存済みの引用は引き続き参照でき、新しい引用も以前の上限で阻止されません。コンテキストには検索に関係した文献を含め、無関係なタイトルを追加しません。',
    ko: 'Research Chat이 대규모 라이브러리와 긴 지시문에서도 자료의 해당 구절을 올바르게 검색합니다. 저장된 인용은 계속 열 수 있으며 새 인용도 이전 제한 때문에 차단되지 않습니다. 컨텍스트에는 질의에 기여한 문헌을 포함하고 관련 없는 제목은 추가하지 않습니다.',
  },
  {
    category: 'fix', scope: 'zotero',
    es: 'El complemento de Nodus para Zotero vuelve a guardar las claves de API y las credenciales de conexión en Zotero 10. Usa el gestor de contraseñas de Zotero y confirma que los datos se han guardado antes de continuar.',
    en: 'The Nodus add-on for Zotero can save API keys and connection credentials in Zotero 10 again. It uses Zotero’s password manager and confirms that credentials have been saved before continuing.',
    fr: 'Le module Nodus pour Zotero peut de nouveau enregistrer les clés API et les identifiants de connexion dans Zotero 10. Il utilise le gestionnaire de mots de passe de Zotero et confirme l’enregistrement avant de continuer.',
    de: 'Das Nodus-Add-on für Zotero speichert API-Schlüssel und Verbindungsdaten in Zotero 10 wieder korrekt. Es verwendet den Passwortmanager von Zotero und bestätigt die Speicherung, bevor es fortfährt.',
    pt: 'O complemento Nodus para o Zotero volta a guardar chaves de API e credenciais de ligação no Zotero 10. Usa o gestor de palavras-passe do Zotero e confirma que as credenciais foram guardadas antes de continuar.',
    'pt-BR': 'O complemento Nodus para o Zotero volta a salvar chaves de API e credenciais de conexão no Zotero 10. Usa o gerenciador de senhas do Zotero e confirma que as credenciais foram salvas antes de continuar.',
    it: 'Il componente aggiuntivo Nodus per Zotero può di nuovo salvare chiavi API e credenziali di connessione in Zotero 10. Usa il gestore di password di Zotero e conferma il salvataggio prima di continuare.',
    tr: 'Zotero için Nodus eklentisi, Zotero 10’da API anahtarlarını ve bağlantı kimlik bilgilerini yeniden kaydedebilir. Zotero’nun parola yöneticisini kullanır ve devam etmeden önce bilgilerin kaydedildiğini doğrular.',
    'zh-CN': 'Nodus 的 Zotero 插件可以重新在 Zotero 10 中保存 API 密钥和连接凭据。插件使用 Zotero 的密码管理器，并在继续操作前确认凭据已保存。',
    'zh-TW': 'Nodus 的 Zotero 外掛可以重新在 Zotero 10 中儲存 API 金鑰和連線憑證。外掛使用 Zotero 的密碼管理員，並在繼續操作前確認憑證已儲存。',
    ja: 'NodusのZoteroアドオンで、Zotero 10にAPIキーと接続認証情報を再び保存できるようになりました。Zoteroのパスワードマネージャーを使用し、保存の完了を確認してから処理を続けます。',
    ko: 'Nodus의 Zotero 부가 기능에서 Zotero 10에 API 키와 연결 인증 정보를 다시 저장할 수 있습니다. Zotero의 비밀번호 관리자를 사용하며 정보가 저장되었는지 확인한 뒤 진행합니다.',
  },
  {
    category: 'fix', scope: 'general',
    es: 'Los paquetes de instalación incluyen solo los archivos de la compilación actual. Se eliminan las copias de compilaciones anteriores para reducir el tamaño de la aplicación.',
    en: 'Installation packages include only files from the current build. Copies from earlier builds are removed to reduce the application’s size.',
    fr: 'Les paquets d’installation contiennent uniquement les fichiers de la compilation actuelle. Les copies des compilations précédentes sont supprimées pour réduire la taille de l’application.',
    de: 'Installationspakete enthalten nur Dateien des aktuellen Builds. Kopien früherer Builds werden entfernt, um die Größe der Anwendung zu verringern.',
    pt: 'Os pacotes de instalação incluem apenas os ficheiros da compilação atual. As cópias de compilações anteriores são removidas para reduzir o tamanho da aplicação.',
    'pt-BR': 'Os pacotes de instalação incluem apenas os arquivos da compilação atual. As cópias de compilações anteriores são removidas para reduzir o tamanho do aplicativo.',
    it: 'I pacchetti di installazione includono solo i file della compilazione attuale. Le copie delle compilazioni precedenti vengono rimosse per ridurre le dimensioni dell’applicazione.',
    tr: 'Kurulum paketleri yalnızca geçerli derlemenin dosyalarını içerir. Uygulamanın boyutunu azaltmak için önceki derlemelerin kopyaları kaldırılır.',
    'zh-CN': '安装包仅包含当前构建的文件。移除了先前构建的副本，以减小应用体积。',
    'zh-TW': '安裝套件僅包含目前建置的檔案。移除了先前建置的副本，以縮小應用程式體積。',
    ja: 'インストールパッケージには現在のビルドのファイルだけが含まれます。以前のビルドのコピーを削除し、アプリのサイズを小さくします。',
    ko: '설치 패키지에는 현재 빌드의 파일만 포함합니다. 이전 빌드의 복사본을 제거하여 애플리케이션 크기를 줄입니다.',
  },
];
